message(STATUS "include Utility.cmake successfully")

function(GetCurrentDirName DirName)
    string(FIND ${CMAKE_CURRENT_SOURCE_DIR} "/" idx REVERSE)
    string(LENGTH ${CMAKE_CURRENT_SOURCE_DIR} len)
    string(SUBSTRING ${CMAKE_CURRENT_SOURCE_DIR} ${idx} ${len} res)
    string(REPLACE "/" "" res ${res})
    set(${DirName} ${res} PARENT_SCOPE)
endfunction()

function(PrintList)
    cmake_parse_arguments("ARG" "" "TITLE;PREFIX" "STR" ${ARGN})
    list(LENGTH ARG_STR len)
    if(NOT len)
        return()
    endif()
    if(NOT "${ARG_TITLE}" STREQUAL "")
        message(STATUS "${ARG_TITLE}")
    endif()
    foreach(str ${ARG_STR})
        message(STATUS "${ARG_PREFIX}${str}")
    endforeach()
endfunction()
