name: Ubuntu

on:
  pull_request:
    types: [main]
  push:
    branches: [main]

jobs:
  build:
    name: "Build ${{ matrix.platform }} in ${{ matrix.build_type }}"
    strategy:
      matrix:
        platform: [ubuntu]
        build_type: [Release]
    env:
      PARALLEL: -j 2
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Configure
        run: cmake -H"." -B"build/${{ matrix.platform }}"

      - name: "Build ${{ matrix.platform }} in ${{ matrix.build_type }}"
        run: cmake --build .