name: Windows_refactor

on:
  pull_request:
    types: [refactor]
  push:
    branches: [refactor]

jobs:
  build:
    name: "Build ${{ matrix.platform }} in ${{ matrix.build_type }}"
    strategy:
      matrix:
        platform: [windows]
        build_type: [Release]
    env:
      PARALLEL: -j 2
    runs-on: "${{ matrix.platform }}-latest"
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: '11.7.0'
          sub-packages: '["nvcc", "visual_studio_integration", "cudart"]'
        run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
        run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
        run: nvcc -V

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build
        run: ./Build_VS2022_Vulkan.bat