name: Windows_refactor

on:
  pull_request:
    types: [refactor]
  push:
    branches: [refactor]

jobs:
  build:
    name: "Build ${{ matrix.platform }} in ${{ matrix.build_type }}"
    strategy:
      matrix:
        platform: [windows]
        build_type: [Release]
    env:
      PARALLEL: -j 2
    runs-on: "${{ matrix.platform }}-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build
        run: ./Build_VS2022_Vulkan.bat